[package]
name = "search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

text_io = "0.1.12"
thirtyfour_sync = "0.27.1"
device_query = "1.1.1"
clipboard = "0.5.0"
